OmniCart/urls.py
from django.contrib import admin
from django.urls import path
from OmniApp.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", index, name="index"),
    path("cart/", view_cart, name="cart"),
    path("register/", RegistrationView.as_view(), name="register"),
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("adminpanel/<uuid:customer_id>", AdminPanelView.as_view(), name="admin_panel"),
    path("add_product/", add_product, name="add_product"),
    path("product-list/", product_list, name="product_list"),
    path("product/edit/<uuid:product_id>/", product_edit, name="product_edit"),
    path("product/delete/<uuid:product_id>/", product_delete, name="product_delete"),
    path("shop/", shop, name="shop"),
    path("shops/", shops, name="shops"),
    path("product/<uuid:product_id>/", product_detail, name="product_detail"),
    path("add_to_cart/<uuid:product_id>/", add_to_cart, name="add_to_cart"),
    path(
        "update-cart-quantity/<int:item_id>/<int:new_quantity>/",
        update_cart_quantity,
        name="update_cart_quantity",
    ),
    path("remove-cart-item/<int:item_id>/", remove_cart_item, name="remove_cart_item"),
    path("checkout/", checkout, name="checkout"),
    path("order-success/<int:order_id>/", order_success, name="order_success"),
    path("orders/", order_list, name="order_list"),
    path("orders/<int:order_id>/", order_detail, name="order_detail"),
    path(
        "orders/<int:order_id>/update-status/",
        update_order_status,
        name="update_order_status",
    ),
    path("get-categories/", get_categories, name="get_categories"),
    path("category/<int:category_id>/", category_view, name="category"),
    path("tags/<int:tag_id>/", tag_view, name="tag"),
    path("get-tags/", get_tag, name="get_tag"),
    path("search/", search_view, name="search_view"),
    path("profile/", my_account, name="my_account"),
    path("shipping-policy/", shipping, name="shipping"),
    path("privacy-policy/", privacy, name="privacy"),
    path("payment-methods/", pymntmethods, name="pymntmethods"),
    path("returns-policy/", returns, name="returns"),
    path("moneyback-policy/", moneyback, name="moneyback"),
    path("aboutus/", about_us, name="about_us"),
    path("contactus/", contact_us, name="contact_us"),
    path("faq/", faq, name="faq"),
    path("help/", help, name="help"),
    path("termsandconditions/", terms_and_condition, name="terms_and_conditions"),
    path("profile-update/", update_customer_info, name="update_customer_info"),
    path("admin-profile/", admin_account, name="admin_account"),
    path(
        "update-admin-customer-info/",
        update_admin_customer_info,
        name="update_admin_customer_info",
    ),
    path("product/<uuid:product_id>/add_review/", add_review, name="add_review"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

OmniApp/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
import uuid
from django.contrib.auth.models import User
from decimal import Decimal
from django.utils import timezone


class CustomUserManager(BaseUserManager):
    def create_user(self, email, username, password=None, **extra_fields):
        if not email:
            raise ValueError("The Email field must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        return self.create_user(email, username, password, **extra_fields)


class Customer(AbstractBaseUser):
    USER_TYPE_CHOICES = [
        ("user", "User"),
        ("manufacturer", "Manufacturer"),
    ]

    id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False, unique=True
    )
    username = models.CharField(max_length=255, unique=True)
    email = models.EmailField(unique=True)
    user_type = models.CharField(max_length=15, choices=USER_TYPE_CHOICES)
    full_name = models.CharField(max_length=255)
    company = models.CharField(max_length=255, null=True, blank=True)
    company_logo_image = models.ImageField(
        upload_to="logo_images/", null=True, blank=True
    )
    country = models.CharField(max_length=255, null=True, blank=True)
    postal_code = models.CharField(max_length=20, blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    phone_number = models.CharField(max_length=20, blank=True, null=True)
    registration_date = models.DateTimeField(auto_now_add=True)
    login_status = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["username"]

    # def __str__(self):
    #     return str(self.id)

    @staticmethod
    def get_customer_by_email(email):
        try:
            return Customer.objects.get(email=email)
        except Customer.DoesNotExist:
            return None

    @staticmethod
    def get_customer_by_username(username):
        try:
            return Customer.objects.get(username=username)
        except Customer.DoesNotExist:
            return None


class Categoryies(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to="category_images/")
    description = models.TextField()

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    product_id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False, unique=True
    )
    product_name = models.CharField(max_length=255)
    manufacturer_id = models.ForeignKey(
        Customer, on_delete=models.CASCADE, related_name="products"
    )
    quantity = models.PositiveIntegerField()
    product_image = models.ImageField(
        upload_to="product_images/", null=True, blank=True
    )
    unit_weight = models.FloatField()
    product_description = models.TextField()
    unit_price = models.DecimalField(max_digits=10, decimal_places=2)
    product_short_description = models.TextField(default=" ")
    categories = models.ManyToManyField(Categoryies, related_name="products")
    tags = models.ManyToManyField(Tag, related_name="products")

    def __str__(self):
        return self.product_name


# Add to Cart Functionality


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default="23223")
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    total_quantity = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.user.username}'s Cart"

    def update_total(self):
        # Calculate total price and quantity based on CartItems
        total_price = Decimal(0)
        total_quantity = 0

        for item in self.items.all():
            total_price += item.product.unit_price * item.quantity
            total_quantity += item.quantity

        # Update the Cart's total price and quantity
        self.total_price = total_price
        self.total_quantity = total_quantity
        self.save()


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, related_name="items", on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def save(self, *args, **kwargs):
        # Update the cart's total price and total quantity when saving a CartItem
        self.cart.total_price += self.product.unit_price * self.quantity
        self.cart.total_quantity += self.quantity
        self.cart.save()
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        # Update the cart's total price and total quantity when deleting a CartItem
        self.cart.total_price -= self.product.unit_price * self.quantity
        self.cart.total_quantity -= self.quantity
        self.cart.save()
        super().delete(*args, **kwargs)

    def __str__(self):
        return f"{self.product.product_name} in {self.cart.user.username}'s Cart"


class Order(models.Model):
    PENDING = "pending"
    PROCESSING = "processing"
    SHIPPED = "shipped"
    DELIVERED = "delivered"

    STATUS_CHOICES = [
        (PENDING, "Pending"),
        (PROCESSING, "Processing"),
        (SHIPPED, "Shipped"),
        (DELIVERED, "Delivered"),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=PENDING)
    order_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Order #{self.id} by {self.user.username}"


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name="items", on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    unit_price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return (
            f"{self.quantity} x {self.product.product_name} in Order #{self.order.id}"
        )


class Review(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="reviews"
    )
    reviewer = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = (
        models.IntegerField()
    )  # You can customize this field based on your rating system
    comment = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)

    class Meta:
        verbose_name = "Review"
        verbose_name_plural = "Reviews"

    def __str__(self):
        return f"Review for {self.product.product_name} by {self.reviewer.username}"

templates/OmniCart/admin/add_product.html
<!-- OmniCart/admin_panel.html -->
{% extends 'OmniCart/admin_panel_layout.html' %}

{% block title %}Manufacturer Admin Panel{% endblock %}

{% block content %}

  <div class="container">
    <div class="row justify-content-center mt-4">
      <div class="col-md-8">
        <h2 class="mb-4">Add Product</h2>
        {% if error_message %}
        <div class="alert alert-danger" role="alert">
          {{ error_message }}
        </div>
      {% endif %}
        <form method="post" id="addProductForm" enctype="multipart/form-data">
          {% csrf_token %}
          
          <div class="mb-3">
            <label for="id_product_name" class="form-label">Product Name:</label>
            {{ form.product_name }}
          </div>
          
          <div class="mb-3">
            <label for="id_quantity" class="form-label">Quantity:</label>
            {{ form.quantity }}
          </div>
          
          <div class="mb-3">
            <label for="id_product_image" class="form-label">Product Image:</label>
            {{ form.product_image }}
          </div>

          <div class="mb-3">
            <label for="id_categories" class="form-label">Categories:</label>
            {{ form.categories }}
        </div>
        
        <div class="mb-3">
            <label for="id_tags" class="form-label">Tags:</label>
            {{ form.tags }}
        </div>
          
          <div class="mb-3">
            <label for="id_unit_weight" class="form-label">Unit Weight:</label>
            {{ form.unit_weight }}
          </div>
          
          <div class="mb-3">
            <label for="id_product_description" class="form-label">Product Description:</label>
            {{ form.product_description }}
          </div>
          <div class="mb-3">
            <label for="id_product_short_description" class="form-label">Product Short Description:</label>
            {{ form.product_short_description }}
          </div>
          
          <div class="mb-3">
            <label for="id_unit_price" class="form-label">Unit Price:</label>
            {{ form.unit_price }}
          </div>
          
          <button type="submit" class="btn btn-primary">Add Product</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/OmniCart/admin/admin-account.html
{% extends 'base.html' %}
{% load static %}
{% block head_title %}Product Detail - {{ product.product_name }}{% endblock %}

{% block content %}

<style>
    body {
        background: #f5f5f5;
        margin-top: 20px;
    }

    .ui-w-80 {
        width: 80px !important;
        height: auto;
    }

    .btn-default {
        border-color: rgba(24, 28, 33, 0.1);
        background: rgba(0, 0, 0, 0);
        color: #4E5155;
    }

    label.btn {
        margin-bottom: 0;
    }

    .btn-outline-primary {
        border-color: #26B4FF;
        background: transparent;
        color: #26B4FF;
    }

    .btn {
        cursor: pointer;
    }

    .text-light {
        color: #babbbc !important;
    }

    .btn-facebook {
        border-color: rgba(0, 0, 0, 0);
        background: #3B5998;
        color: #fff;
    }

    .btn-instagram {
        border-color: rgba(0, 0, 0, 0);
        background: #000;
        color: #fff;
    }

    .card {
        background-clip: padding-box;
        box-shadow: 0 1px 4px rgba(24, 28, 33, 0.012);
    }

    .row-bordered {
        overflow: hidden;
    }

    .account-settings-fileinput {
        position: absolute;
        visibility: hidden;
        width: 1px;
        height: 1px;
        opacity: 0;
    }

    .account-settings-links .list-group-item.active {
        font-weight: bold !important;
    }

    html:not(.dark-style) .account-settings-links .list-group-item.active {
        background: transparent !important;
    }

    .account-settings-multiselect~.select2-container {
        width: 100% !important;
    }

    .light-style .account-settings-links .list-group-item {
        padding: 0.85rem 1.5rem;
        border-color: rgba(24, 28, 33, 0.03) !important;
    }

    .light-style .account-settings-links .list-group-item.active {
        color: #4e5155 !important;
    }

    .material-style .account-settings-links .list-group-item {
        padding: 0.85rem 1.5rem;
        border-color: rgba(24, 28, 33, 0.03) !important;
    }

    .material-style .account-settings-links .list-group-item.active {
        color: #4e5155 !important;
    }

    .dark-style .account-settings-links .list-group-item {
        padding: 0.85rem 1.5rem;
        border-color: rgba(255, 255, 255, 0.03) !important;
    }

    .dark-style .account-settings-links .list-group-item.active {
        color: #fff !important;
    }

    .light-style .account-settings-links .list-group-item.active {
        color: #4E5155 !important;
    }

    .light-style .account-settings-links .list-group-item {
        padding: 0.85rem 1.5rem;
        border-color: rgba(24, 28, 33, 0.03) !important;
    }
</style>

<div class="container-fluid bg-secondary mb-5">
    <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 300px">
        <h1 class="font-weight-semi-bold text-uppercase mb-3">Account Setting</h1>
        <div class="d-inline-flex">
            <p class="m-0"><a href="{% url 'index' %}">Home</a></p>
            <p class="m-0 px-2">-</p>
            <p class="m-0">Profile</p>
        </div>
    </div>
</div>

<div class="container light-style flex-grow-1 container-p-y mb-3">

    <!-- Page Header Start -->

    <!-- Page Header End -->

    <div class="card overflow-hidden">
        <div class="row no-gutters row-bordered row-border-light">
            <div class="col-md-3 pt-0">
                <div class="list-group list-group-flush account-settings-links">
                    <a class="list-group-item list-group-item-action active" data-toggle="list"
                        href="#account-general">General</a>
                    <!-- <a class="list-group-item list-group-item-action" data-toggle="list" href="#account-change-password">Change password</a> -->
                    <a class="list-group-item list-group-item-action" data-toggle="list" href="#account-info">Info</a>

                    <a class="list-group-item list-group-item-action" data-toggle="list"
                    href="#account-pending-orders">Pending Order</a>
                    
                </div>
            </div>
            <div class="col-md-9">
                <div class="tab-content">
                    <div class="tab-pane fade active show" id="account-general">

                        <div class="card-body media align-items-center">
                            <img src="https://bootdey.com/img/Content/avatar/avatar1.png" alt=""
                                class="d-block ui-w-80">
                            <!-- <div class="media-body ml-4">
                  <label class="btn btn-outline-primary">
                    Upload new photo
                    <input type="file" class="account-settings-fileinput">
                  </label> &nbsp;
                  <button type="button" class="btn btn-default md-btn-flat">Reset</button>

                  <div class="text-light small mt-1">Allowed JPG, GIF or PNG. Max size of 800K</div>
                </div> -->
                        </div>
                        <hr class="border-light m-0">

                        <div class="card-body">
                            <div class="form-group">
                                <label class="form-label">Username</label>
                                <input type="text" class="form-control mb-1" value="{{ customer.username }}" readonly>
                            </div>

                            <div class="form-group">
                                <label class="form-label">E-mail</label>
                                <input type="text" class="form-control mb-1" value="{{ customer.email }}" readonly>

                            </div>

                        </div>

                    </div>
                    <!-- <div class="tab-pane fade" id="account-change-password">
              <div class="card-body pb-2">

                <div class="form-group">
                  <label class="form-label">Current password</label>
                  <input type="password" class="form-control">
                </div>

                <div class="form-group">
                  <label class="form-label">New password</label>
                  <input type="password" class="form-control">
                </div>

                <div class="form-group">
                  <label class="form-label">Repeat new password</label>
                  <input type="password" class="form-control">
                </div>

              </div>
            </div> -->
                    <div class="tab-pane fade" id="account-info">
                        <form action="{% url 'update_admin_customer_info' %}" method="post"
                            enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="card-body pb-2">

                                <div class="form-group">
                                    <label class="form-label">Name</label>
                                    <input type="text" class="form-control" name="full_name"
                                        value="{{ customer.full_name }}">
                                </div>

                                <div class="form-group">
                                    <label class="form-label">Address</label>
                                    <textarea class="form-control" name="address"
                                        rows="5">{{ customer.address }}</textarea>
                                </div>

                                <div class="form-group">
                                    <label class="form-label">Country</label>
                                    <input type="text" class="form-control" name="country"
                                        value="{{ customer.country }}">
                                </div>
                                <div class="form-group">
                                    <label class="form-label">Postal Code</label>
                                    <input type="number" class="form-control" name="postal_code"
                                        value="{{ customer.postal_code }}">
                                </div>


                            </div>
                            <hr class="border-light m-0">
                            <div class="card-body pb-2">

                                <h6 class="mb-4">Contacts</h6>

                                <div class="form-group">
                                    <label class="form-label">Phone</label>
                                    <input type="text" class="form-control" name="phone_number"
                                        value="{{ customer.phone_number }}">
                                </div>
                                <div class="form-group">
                                    <label class="form-label">Company</label>
                                    <input type="text" class="form-control" name="company"
                                        value="{{ customer.company }}">
                                </div>
                                {% if customer.company_logo_image %}
    <div class="form-group">
        <label class="form-label">Current Company Logo</label>
        <img src="{{ customer.company_logo_image.url }}" alt="Current Company Logo" width="100">
    </div>
{% endif %}
                                <div class="form-group">
                                    <label class="form-label">Company logo</label>
                                    <input type="file" class="form-control" name="company_logo">
                                </div>


                                <div class="text-right mt-3 mb-3">
                                    <input type="hidden" name="customer_id" value="{{ customer.id }}">
                                    <button type="submit" class="btn btn-primary">Save changes</button>&nbsp;
                                    <button type="button" class="btn btn-default">Cancel</button>
                                </div>
                        </form>

                    </div>
                    <div class="tab-pane fade" id="account-social-links">
                        <div class="card">
                            <div class="card-header">
                                <h5 class="card-title">Pending Orders</h5>
                            </div>
                            <div class="card-body pb-2">
                                {% if pending_orders %}
                                <ul class="list-group">
                                    {% for order in pending_orders %}
                                    <li class="list-group-item">
                                        <div class="row">
                                            <div class="col-6">
                                                <span class="font-weight-bold">Order ID:</span> {{ order.id }}
                                            </div>
                                            <div class="col-6 text-right">
                                                <span class="font-weight-bold">Total Price:</span> {{ order.total_price
                                                }}
                                                <span class="badge text-bg-warning">{{ order.status }}</span>
                                            </div>
                                        </div>
                                    </li>

                                    {% endfor %}
                                </ul>
                                {% else %}
                                <p>No pending orders.</p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
</div>
                    <div class="tab-pane fade" id="account-pending-orders">
                        <div class="card">
                            <div class="card-header">
                                <h5 class="card-title">Pending Orders</h5>
                            </div>
                            <div class="card-body pb-2">
                                {% if pending_orders %}
                                <ul class="list-group">
                                    {% for order in pending_orders %}
                                    <li class="list-group-item">
                                        <div class="row">
                                            <div class="col-6">
                                                <span class="font-weight-bold">Order ID:</span> {{ order.id }}
                                            </div>
                                            <div class="col-6 text-right">
                                                <span class="font-weight-bold">Total Price:</span> {{ order.total_price }}
                                                <span class="badge text-bg-warning">{{ order.status }}</span>
                                            </div>
                                        </div>
                                    </li>

                                    {% endfor %}
                                </ul>
                                {% else %}
                                <p>No pending orders.</p>
                                {% endif %}
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>


</div>

{% endblock content %}

templates/OmniCart/admin/product_edit.html
{% extends 'OmniCart/admin_panel_layout.html' %}

{% block title %}Edit Product{% endblock %}

{% block content %}
  <div class="container">
    <h2 class="mt-4 mb-4">Edit Product</h2>

    <form method="POST" id="addProductForm" enctype="multipart/form-data">
      {% csrf_token %}
      
      <div class="mb-3">
        <label for="id_product_name" class="form-label">Product Name:</label>
        <input type="text" name="product_name" id="id_product_name" class="form-control" value="{{ product.product_name }}">
      </div>
      
      <div class="mb-3">
        <label for="id_quantity" class="form-label">Quantity:</label>
        <input type="number" name="quantity" id="id_quantity" class="form-control" value="{{ product.quantity }}">
      </div>
      
      <div class="mb-3">
        <label for="id_product_image" class="form-label">Product Image:</label>
        <input type="file" name="product_image" id="id_product_image" class="form-control-file">
        <img src="{{ product.product_image.url }}" alt="{{ product.product_name }}" style="max-width: 100px;">
      </div>
      
      <div class="mb-3">
        <label for="id_unit_price" class="form-label">Unit Price:</label>
        <input type="text" name="unit_price" id="id_unit_price" class="form-control" value="{{ product.unit_price }}">
      </div>
      
      <div class="mb-3">
        <label for="id_categories" class="form-label">Categories:</label>
        {{ form.categories }}
    </div>
    
    <div class="mb-3">
        <label for="id_tags" class="form-label">Tags:</label>
        {{ form.tags }}
    </div>

      <div class="mb-3">
        <label for="id_unit_weight" class="form-label">Unit Weight:</label>
        <input type="text" name="unit_weight" id="id_unit_weight" class="form-control" value="{{ product.unit_weight }}">
    </div>
    
    <div class="mb-3">
        <label for="id_product_description" class="form-label">Product Description:</label>
        <textarea name="product_description" id="id_product_description" class="form-control" rows="4">{{ product.product_description }}</textarea>
    </div>
    <div class="mb-3">
      <label for="id_product_short_description" class="form-label">Product Short Description:</label>
      <textarea name="product_short_description" id="id_product_short_description"  class="form-control" rows="2">{{ product.product_short_description }}</textarea>
  </div>

      <button type="submit" class="btn btn-primary">Update Product</button>
    </form>
  </div>
{% endblock %}

templates/OmniCart/admin/product_list.html
{% extends 'OmniCart/admin_panel_layout.html' %}

{% block title %}Product List{% endblock %}

{% block content %}
  <div class="container" >
    <h2 class="mt-4 mb-4">Product List</h2>

    {% if products %}
      <table id="myTable" class="table display">
        <thead>
          <tr>
            <th scope="col">Product Image</th>
            <th scope="col">Product Name</th>
            <th scope="col">Unit Price</th>
            <th scope="col">Stock</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for product in products %}
            <tr>
              <td><img src="{{ product.product_image.url }}" alt="{{ product.product_name }}" style="max-width: 100px;"></td>
              <td>{{ product.product_name }}</td>
              <td>₹{{ product.unit_price }}</td>
              <td>{{ product.quantity }}</td>
              <td>
                <a href="{% url 'product_edit' product_id=product.product_id %}"><i class='bx bx-edit-alt' ></i></a>
                <!-- this is a delete  -->
                <a href="" token="{{ csrf_token }}" class="delete-product" data-product-id="{{ product.product_id }}"><i class="bx bx-trash"></i></a>
                {% if product.disabled %}
                  <i class="bx bx-x"></i> 
                {% else %}
                  <i class="bx bx-check"></i>
                {% endif %}
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p>No products available.</p>
    {% endif %}
  </div>

{% endblock %}